name: Validate

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install uv & Python
        uses: astral-sh/setup-uv@v7
        with:
          version: 0.9.21
          python-version: "3.11"
          enable-cache: true

      - name: Lint
        run: |
          uvx isort --check-only src tests
          uvx black --diff --check src tests

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install uv & Python
        uses: astral-sh/setup-uv@v7
        with:
          version: 0.9.21
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: Install dependencies
        run: uv sync --locked --all-extras --dev

      - name: Run tests
        run: uv run pytest --cov=. --cov-branch --cov-fail-under=80 tests

  doc:
    runs-on: ubuntu-latest

    env:
      VERSION: ${{ github.ref_name }}
      
    steps:
      - name: Install uv & Python
        uses: astral-sh/setup-uv@v7
        with:
          version: 0.9.21
          python-version: "3.11"
          enable-cache: true

      - name: Build doc
        run: |
          uv run pdoc --math -d google --no-include-undocumented -t .github/doc/ -o docs/ aiice

      - uses: actions/upload-pages-artifact@v4
        with:
          path: docs/
    
  deploy:
    needs: doc
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v5
